cloudfoundry/csb-brokerpak-azure

terraform/azure-mysql/provision-mysql.tf

I have found that MySQL instance creation fails intermittently when authorized_networks is configured and after playing around with changes adding a dependency such the DB itself is created before the FW and authorized networks rules are created seems to resolve this.

Add dependency on MySQL DB instance for FW/authorized network rules

---

Makefile
acceptance-tests/azure/cf-test-spring-music-service.sh
azure-mssql-failover.yml

Since https://github.com/cloudfoundry/cloud_controller_ng/commit/8a4926db17807b2cad1736614784f0c57ba49336,
Cloud Foundry will fail if a broker uses duplicate IDs for plans as they should be universally unique.
Because some users will be upgrading from earlier versions of Cloud
Foundry we have changed the duplicate plan ID and name. This means that
users will have to update exisitng "small" services to be "small-v2"
after upgrading. But by changing both the name and the ID we avoid
an error occuring where the same name is associated with more than one
ID.
[#177727007](https://www.pivotaltracker.com/story/show/177727007)

fix: remove duplicate plan ID

---

Makefile
terraform/azure-mongodb/azure-mongodb.tf
terraform/azure-mssql-db-failover/mssql-db-fog-main.tf
terraform/azure-mssql-failover/provision-mssql-failover.tf

Following on from cd7c9f7 there need to be some updates to the Terraform
in order to be compliant with the new provider version:
- secondary DBs cannot have the size set as this is computed from the
primary
- Cosmos Mongo needs the shard index to also be defined as a unique
index
Also updated the Makefile to add some user help
[#178142486](https://www.pivotaltracker.com/story/show/178142486)

Update Terraform for new provider version

---

manifest.yml

The file isn't used, and the only purpose for it seems to have been that
the 'source' field was mandatory in the past.
[#178265962](https://www.pivotaltracker.com/story/show/178265962)

fix: stop including packages-microsoft-prod.rpm in Azure brokerpak

---

acceptance-tests/azure/cf-test-spring-music-service.sh
azure-mssql.yml

Previous fix #34 was sufficient to allow the brokerpak to install on a
fresh TAS 2.11 system, but upgrades from previous versions of Cloud Foundry
failed because there was still a reference to the duplicated ID in the
Cloud Foundry database. By removing all references to
`a556d1b4-5825-11ea-adb8-00155d4dfe6c`, we make sure that this error
cannot occur, although it does mean that service instances of two plans
will need to be updated to the *-v2 version of the plan.
[#178330774](https://www.pivotaltracker.com/story/show/178330774)

fix: remove duplicate plan ID (part 2)

---

azure-mysql.yml
azure-redis.yml
terraform/azure-mysql/provision-mysql.tf
terraform/azure-redis/redis-provision.tf

Adds new plan inputs `private_endpoint_subnet_id` and `private_dns_zone_ids` to support creating Private Endpoints during provisioning.

Private Endpoint support for Redis and MySQL

---

acceptance-tests/helpers/cf_version.go
acceptance-tests/helpers/service.go
acceptance-tests/helpers/service_key.go

CF CLI v8 will introduce some useful changes for services, specifically
the --wait flag for creating and deleting service instances. It also
introduces some incidental features such as a subtle difference in
output for the "cf service-key" command. This change allows the tests to
run with CF 8 and use the --wait flag, or to run on earlier versions and
still work

test: tests should work on CF 8, and earlier

---

azure-mysql.yml

When we try to create a MySQL 5.6 database we get:
```
Code="InvalidVersion" Message="Version '5.6' is not supported."
```
So we should update the examples test. It's probably just testing a
non-default version, so updated to test v8. Decided not to remove v5.6
from the allowed version enum because this might cause issues for people
who already have a v5.6 DB and are doing an update-service.
[#179433132](https://www.pivotaltracker.com/story/show/179433132)

test: update examples to no longer use MySQL 5.6

---

acceptance-tests/mssql/mssql_failover_group_test.go
terraform/azure-mssql/bind-mssql.tf

This relates to the `csb-azure-mssql-failover-group` service offering.
By creating the user in the `master` database on the primary, it seems
that the user was not propagated to the secondary. The fix is
copied from the csb-azure-mssql-db-failover-group service and results in
the user appearing in both the primary and secondary databases.
[#179168006](https://www.pivotaltracker.com/story/show/179168006)

fix: binding DB user should also be in replica

---

acceptance-tests/apps/postgresqlapp/internal/app/app.go
acceptance-tests/apps/postgresqlapp/internal/app/create_schema.go
acceptance-tests/apps/postgresqlapp/internal/app/drop_schema.go
acceptance-tests/apps/postgresqlapp/internal/app/get.go
acceptance-tests/apps/postgresqlapp/internal/app/set.go
acceptance-tests/postgresql/postgresql_test.go
terraform/azure-postgres/postgresql-bind.tf

By default each user (which corresponds to each binding) is provided
with a private schema and has no access to other schemas. This means
that if two apps connect to the same service instance they see different
data, and if an app is re-bound it sees different data. By giving the
user permissions to create a schema, apps can create schemas that other
bindings can see.
This is the same fix as done for AWS: https://github.com/cloudfoundry-incubator/csb-brokerpak-aws/commit/cb6b8caeb0601ab2b503d231d6639a5953b525b7
[#179125219](https://www.pivotaltracker.com/story/show/179125219)

fix: PostgreSQL user needs permissions to create schema

---

acceptance-tests/helpers/apps/push.go
acceptance-tests/helpers/service.go
acceptance-tests/helpers/service_broker.go
acceptance-tests/mongodb/mongodb_test.go
acceptance-tests/upgrade/README.md
acceptance-tests/upgrade/update_and_upgrade_cosmos_test.go
acceptance-tests/upgrade/update_and_upgrade_mongodb_test.go
acceptance-tests/upgrade/update_and_upgrade_mssql_db_failover_test.go
terraform/azure-mongodb/azure-mongodb.tf

- explicitely enable mongo API through capabilities. Without this there is an
account recreation on update
- add required _id index. Some context for this change in https://github.com/hashicorp/terraform-provider-azurerm/issues/8144#issuecomment-686955895
This PR doesn't have tests yet and therefore is draft. It was tested manually only.
[#180197227](https://www.pivotaltracker.com/story/show/180197227)

Fix issues with mongodb update

---

acceptance-tests/mongodb/mongodb_test.go
acceptance-tests/mssql-server-pair/mssql_server_pair_and_fog_db_test.go
acceptance-tests/mssql-server-pair/mssql_server_suite_test.go

- MongoDB test was taking 54 mins and mssql-server 34 mins
- splits the mssql-server tests into separate directories so that it's
easier to run the two tests in parallel.
- removes the plan change from MongoDB. This was useful for seeing that
a bug had been fixed, but it's too slow for a forever test.
- longest running test is now Redis at 32 mins, but there are no easy
improvements for that one
[#180197227](https://www.pivotaltracker.com/story/show/180197227)

test: improve speed

---

acceptance-tests/apps/mssqlapp/internal/app/create_schema.go
acceptance-tests/upgrade/update_and_upgrade_mssql_test.go

- as part of the fix in [180314427](https://www.pivotaltracker.com/story/show/180314427) we
can now check that data persists after unbinding/rebinding to a mssql service.
[#180330326](https://www.pivotaltracker.com/story/show/180330326)

test: mssql upgrade test checks data retention after unbind/bind

---

acceptance-tests/mongodb/mongodb_test.go
acceptance-tests/upgrade/update_and_upgrade_mongodb_test.go

The test was updated to use medium->large plan change to rule out a
potential issue with the small plan. But we now now that the
small->medium plan change works just as well, so we should use that as
the main test since it may be faster and use less resources.
[#180197227](https://www.pivotaltracker.com/story/show/180197227)

test(mongodb): use smaller plans

---

acceptance-tests/mssql_db_subsume_test.go
acceptance-tests/mssql_fog_db_subsume_test.go
azure-mssql-db-failover.yml
azure-mssql-db.yml
docs/draft-release-notes.md

tf_attribute set to extract the fields from the tf state during update
[#180586187](https://www.pivotaltracker.com/story/show/180586187)

fix: Incompatibility of HCL update and subsume

---

azure-postgres.yml
docs/draft-release-notes.md

fix: minimum constraint on storage_gb for PostgreSQL

---

Makefile
tools/psqlcmd/Makefile
tools/sqlfailover/Makefile

- new check only prints when there is an error
- new check does not allow substring matches
[#181960182](https://www.pivotaltracker.com/story/show/181960182)

chore: improve Go version check

---

acceptance-tests/apps/cosmosdbapp/package-lock.json
acceptance-tests/apps/storageapp/package-lock.json

I noticed an "npm audit" issue when installing the NPM storage app,
so I accepted the fix offered by "npm audit fix". Dependabot looks like
it's correctly set up, but not offering a fix for this.

chore: update npm test packages for security

---

acceptance-tests/helpers/apps/push.go
acceptance-tests/helpers/brokers/create.go

Each broker and test app was allocated 1GB, which is far more than they
actually need. Reduced to about double what they need to give them some head
room.
[#182571088](https://www.pivotaltracker.com/story/show/182571088)

chore: put upgrade tests on memory diet

---

acceptance-tests/upgrade/update_and_upgrade_mssql_db_failover_test.go

now that we are upgrading the tf version between brokers
we must upgrade all the previous service instances to allow
test cleanup.
[#182635325](https://www.pivotaltracker.com/story/show/182635325)
~* [ ] Have you added Draft Release Notes in `docs/draft-release-notes.md`?~

test: upgrade all services to enable cleanup

---

acceptance-tests/upgrade/update_and_upgrade_redis_test.go

Reverting back to previous test structure which did not
assert that data persists after plan update. Only checking
that upgrade does not result in data loss.
[#182635325](https://www.pivotaltracker.com/story/show/182635325)
~* [ ] Have you added Draft Release Notes in `docs/draft-release-notes.md`?~

test: only assert data available after upgrade

---

terraform/azure-mssql-db-failover/mssql-db-fog-main.tf
terraform/azure-mssql-db-failover/mssql-db-fog-outputs.tf

on versions of Terraform >0.12 the outputs were failing
as they were being validated while the primary_db resource was
still null. This change ensures that either a null value or correct
value is returned, whereas previously we were indexing an empty object
causing a failure.
More info on the [one function](https://www.terraform.io/language/functions/one)
[#182635325](https://www.pivotaltracker.com/story/show/182635325)
~* [ ] Have you added Draft Release Notes in `docs/draft-release-notes.md`?~

fix: use one() function to pass TF syntax check

---

providers/terraform-provider-csbmssqldbrunfailover/Makefile
providers/terraform-provider-csbsqlserver/Makefile

A well-intentioned optimisation has broken the ability to build a
brokerpak on a Mac. This is because on a Mac it's necessary to
cross-compile linux binaries, and Mac binaries are often useful too for
being able to run locally. We should probably avoid building Mac binaries
on a Linux desktop, and that could be a future enhancement.
* ~~[ ] Have you added Draft Release Notes in `docs/draft-release-notes.md`?~~ break and fix will be in same release

fix: build brokerpak on Mac

---

manifest.yml

- In previous versions, a `~>` provider version constraint was used
which restricts the version to patch fixes only.
- In this version we will update all the HCL with this constraint, but
just before the upgrade process we will perform a "terraform show" which
will evaluate the `~>` constraint and will fail if the matching version
of the provider is not present.
- Versions 2.33.0 and 2.20.0 have been shipped previously, and this
change adds both of those versions back until we are sure that all
customers have upgraded and the `~>` constraint is no longer in use.
* ~~[x] Have you added Draft Release Notes in `docs/draft-release-notes.md`?~~ part of upgrade feature

fix: restore azurerm@v2.33 and v2.20 Terraform providers

---

terraform/azure-mongodb/azure-mongodb.tf

In #236 we added lifecycle.prevent_destroy to many object as a backstop
in case an updates attempted to destroy data. We have discovered that
the MongoDB account must also be preserved, as when it gets re-created
the originally written data cannot be accessed.
* ~~[x] Have you added Draft Release Notes in `docs/draft-release-notes.md`?~~ extension of a feature in this release

fix: add additional lifecycle.prevent_destroy to MongoDB

---

acceptance-tests/helpers/apps/app.go
acceptance-tests/helpers/apps/push.go
acceptance-tests/helpers/brokers/create.go
cf-manifest.yml

The brokerpak zip now contains many versions of Terraform and some
providers. Because of this the app is using more than 1GB of disk space.
This change increases the disk space allocated to the app.

chore: increase disk usage for Azure brokerpak

---

acceptance-tests/apps/mssqlapp/internal/app/app.go
acceptance-tests/apps/mssqlapp/internal/app/create_schema.go
acceptance-tests/apps/mssqlapp/internal/app/drop_schema.go
acceptance-tests/apps/mssqlapp/internal/app/fill_db.go
acceptance-tests/apps/mssqlapp/internal/app/get.go
acceptance-tests/apps/mssqlapp/internal/app/set.go
acceptance-tests/upgrade/update_and_upgrade_mssql_test.go

- In the past it was not possible to create a schema with DBO ownership. This caused problems relating to deleting bindings (if they owned a schema), so it has been fixed. But when testing an upgrade, we need to test from a version that has not been fixed
- The test app has been modified to be able to create a schema with or without DBO ownership
- The test app has been updated to reduce duplication in error handling and to log more error details
- A new "ancient" test has been added, which is a cut down version of the existing test. This tests the upgrade with data, without hitting the binding ownership issues above

test: mssql upgrade from ancient brokerpak

---

acceptance-tests/upgrade/update_and_upgrade_mssql_db_failover_test.go
acceptance-tests/upgrade/update_and_upgrade_mssql_db_test.go
acceptance-tests/upgrade/update_and_upgrade_mssql_failover_group_test.go
azure-mssql-db-failover.yml
azure-mssql-failover.yml

Ancient brokerpaks don't have all the fixes, so we need to modify some
of the upgrade tests so that we test data retention without hitting
known issues from these old versions.

test: new upgrade tests for ancient brokerpaks

---

acceptance-tests/apps/mongodbapp/internal/app/app.go
acceptance-tests/apps/mongodbapp/internal/app/fetch_document.go
acceptance-tests/apps/mssqlapp/internal/app/app.go
acceptance-tests/apps/mssqlapp/internal/credentials/config.go
acceptance-tests/apps/mysqlapp/internal/app/app.go
acceptance-tests/apps/postgresqlapp/internal/app/app.go
acceptance-tests/apps/redisapp/internal/app/app.go
acceptance-tests/cosmosdb_test.go
acceptance-tests/helpers/apps/http.go
acceptance-tests/helpers/apps/setenv.go
acceptance-tests/helpers/bindings/credential.go
acceptance-tests/helpers/serverpairs/serverpairs.go
acceptance-tests/helpers/servicekeys/get.go
acceptance-tests/helpers/services/create.go
acceptance-tests/mongodb_test.go
acceptance-tests/mssql_db_subsume_test.go
acceptance-tests/mssql_failover_group_test.go
acceptance-tests/mssql_fog_db_subsume_test.go
acceptance-tests/mssql_server_and_db_test.go
acceptance-tests/mssql_server_pair_and_fog_db_test.go
acceptance-tests/upgrade/update_and_upgrade_cosmos_test.go
acceptance-tests/upgrade/update_and_upgrade_mongodb_test.go
acceptance-tests/upgrade/update_and_upgrade_mssql_db_failover_group_test.go
acceptance-tests/upgrade/update_and_upgrade_mssql_db_test.go
acceptance-tests/upgrade/update_and_upgrade_mssql_failover_group_test.go

Go 1.18 introduced the alternative of 'any' for the rather awkward
'interface{}'. Since this came out we have been using a mixture in this
project. This PR updates code (except generated code) to consistently
use `any` since it's easier to type and to understand.

chore: replace 'interface{}' with 'any'

---

providers/terraform-provider-csbsqlserver/connector/connector.go

It's good practice to use database transactions when performing related
database tasks, and this change introduces transactions for creating and
deleting the binding, so that the operation should either happen (or not
happen) atomically
[#182986768](https://www.pivotaltracker.com/story/show/182986768)

chore: SQL-Server provider should use DB transactions

---

.gitignore
docs/draft-release-notes.md
providers/terraform-provider-csbmssqldbrunfailover/csbmssqldbrunfailover/config.go
providers/terraform-provider-csbmssqldbrunfailover/csbmssqldbrunfailover/csbmssqldbrunfailover_suite_test.go
providers/terraform-provider-csbmssqldbrunfailover/csbmssqldbrunfailover/provider.go
providers/terraform-provider-csbmssqldbrunfailover/csbmssqldbrunfailover/provider_test.go
providers/terraform-provider-csbmssqldbrunfailover/csbmssqldbrunfailover/resource_run_failover_test.go

Fix a problem when logging the secret value.
We remove the regex introducing less restrictive validations. The validation is on the supplier’s side and we just check if the field is empty or too long.
[#183032358](https://www.pivotaltracker.com/story/show/183032358)
[#183032253](https://www.pivotaltracker.com/story/show/183032253)

fix: a problem when logging the secret value in terraform-provider-csbmssqldbrunfailover

---

Makefile

Reverts cloudfoundry/csb-brokerpak-azure#321

Revert "chore: "make run" should target current platform"

---

acceptance-tests/helpers/brokers/manifest.go

I'm seeing a number of intermittent failures when starting the broker app
like:
```
2022-08-31T03:11:33.90+0000 [APP/PROC/WEB/0] ERR panic: error loading brokerpaks: error extracting versioned terraform binary: couldn't extract file "bin/linux/amd64/0.14.11/terraform": copy couldn't copy data: write /home/vcap/tmp/brokerpak1632791266/versions/0.14.11/terraform: cannot allocate memory
```
Hopefully a bit more memory will make them go away.

test: increase broker app memory

---

Makefile

This re-introduces #321 that was reverted in #331
We think this is safe after fix https://github.com/cloudfoundry/cloud-service-broker/pull/605
This reverts commit 8e7b9699ae333b34216f8aed1ae5f01fbb36b33a.
The "make run" command starts a CSB. Previously, when running on a Mac
it was necessary to update the manifest to make sure that Darwin
binaries were added to the brokerpak. But now we can make use of the new
"csb pak build --target" flag to do this automatically.
[#181407433](https://www.pivotaltracker.com/story/show/181407433)

chore: "make run" should target current platform x2

---

integration-tests/integration_test_suite_test.go

integration tests were failing as we were not copying the service
image across when building the brokerpak.
[#183058257](https://www.pivotaltracker.com/story/show/183058257)

test: fix integration tests - add service-image

---

acceptance-tests/mssql_fog_existing_test.go
acceptance-tests/upgrade/update_and_upgrade_mssql_db_failover_group_test.go
acceptance-tests/upgrade/update_and_upgrade_mssql_failover_group_existing_test.go

An issue was found when upgrading the
"csb-azure-mssql-db-failover-group" service with the "existing" plan. This is because the "existing" plan connects to an existing FOG, and therefore expectations about what's in the Terraform state file don't match. This test replicates the failure so that the upgrade can be tested in future and the fix can be validated.
[#183463447](https://www.pivotaltracker.com/story/show/183463447)

test: csb-azure-mssql-db-failover-group existing upgrade

---

terraform/azure-cosmosdb/provision-cosmosdb-sql.tf
terraform/azure-eventhubs/azure-eventhubs-bind.tf
terraform/azure-eventhubs/azure-eventhubs.tf
terraform/azure-mongodb/azure-mongodb.tf
terraform/azure-mssql-db-failover/run-failover/run-failover-providers.tf
terraform/azure-mssql-db/bind/mssql-bind-variables.tf
terraform/azure-mssql-db/provision/mssql-db-providers.tf
terraform/azure-mssql-db/provision/mssql-db-variables.tf
terraform/azure-mssql-failover/provision-mssql-failover.tf
terraform/azure-mssql-server/mssql-server-provision.tf
terraform/azure-mssql/bind-mssql.tf
terraform/azure-mssql/provision-mssql.tf
terraform/azure-mysql/bind-mysql.tf
terraform/azure-mysql/provision-mysql.tf
terraform/azure-postgres/postgres-provision.tf
terraform/azure-postgres/postgresql-bind.tf
terraform/azure-redis/redis-provision.tf
terraform/azure-resource-group/resource-group-provision.tf
terraform/azure-storage/account-provision.tf

terraform will display sensitive values in debug logs if not instructured to redact them. This adds redaction to possible sources for credential leaks in the tf input / output data.
[ #183474479 ]
~* [ ] Have you added Release Notes in the docs repositories?~

feat: mark sensitive values in var inputs and outputs

---

acceptance-tests/redis_test.go
acceptance-tests/upgrade/update_and_upgrade_redis_test.go
azure-redis.yml
integration-tests/redis_test.go
terraform/azure-redis/redis-provision.tf

Customers should be moving to their own plan definitions and they should use v6 redis version
[#183863818](https://www.pivotaltracker.com/story/show/183863818)

feat: Redis - Mark brokerpak plans as deprecated

---

acceptance-tests/apps/cosmosdbapp/index.js
acceptance-tests/apps/storageapp/package-lock.json
acceptance-tests/apps/storageapp/package.json
acceptance-tests/cosmosdb_test.go

CosmosDB acceptance test uses an application to write and retrieve data. The data is parsed using a library jsonata.
The public API of the library changed and now is an asynchronous API.
[#184085630](https://www.pivotaltracker.com/story/show/184085630)

chore: fix CosmosDB acceptance test

---

acceptance-tests/helpers/apps/prebuild.go

In the GCP brokerpak we increased the timeout for test app prebuild to 5 minutes, and it reduced test flakes. In order to fix similar flakes, we should increase the timeout in this brokerpak too.

test: increase pre-build timeout to match GCP

---

azure-storage-account.yml

The storage account service should use the same image as every other service. It looks like it was missed when they were all updated.

fix: image for storage account

---

integration-tests/cosmosdb_sql_test.go
integration-tests/eventhubs_test.go
integration-tests/integration_test_suite_test.go
integration-tests/mongodb_test.go
integration-tests/mssql_failover_test.go
integration-tests/mssql_server_test.go
integration-tests/mssql_test.go
integration-tests/mysql_test.go
integration-tests/postgre_sql_test.go
integration-tests/redis_test.go
integration-tests/resource_group_test.go
integration-tests/storage_account_test.go

This is to match the testing style in the GCP and AWS brokerpaks

test: add catalog tests to integration tests

---

providers/terraform-provider-csbmssqldbrunfailover/Makefile
providers/terraform-provider-csbsqlserver/Makefile

The custom Terraform providers should be statically linked. It looks like a change in Go 1.20 resulted in them being dynamically linked when built on Linux, and then they didn't work in the CSB app because the binary buildpack doesn't have the required libraries available. This change ensures that they are statically linked.
[#184404359](https://www.pivotaltracker.com/story/show/184404359)

chore: ensure that custom providers are statically linked

---

azure-redis.yml
integration-tests/redis_test.go

- Prior to 1.4.0 there was no "redis_version" property.
- In 1.4.0 the redis_version property was added, and existing plans were changed to specify redis_version=4. This was sensible at the time since previous versions created Redis v4 instance.
- Recently a test started to fail because new Redis instances created with brokerpak versions prior to 1.4.0 started to default to Redis v6 instances. This meant that when trying to upgrade to 1.4.0 or higher, an attempt was made to change the Redis version from v6 -> v4, resulting in the error:
properties.redisVersion cannot be updated to 4.
- To resolve this, the value of redis_version for existing plans has been removed so that the Azure default will be used. This allows the upgrade to succeed for Redis v6. …

fix: Redis upgrade from brokerpak 1.4.0

---

manifest.yml
terraform/azure-cosmosdb/provision-cosmosdb-sql.tf
terraform/azure-eventhubs/azure-eventhubs-bind.tf
terraform/azure-eventhubs/azure-eventhubs.tf
terraform/azure-mongodb/azure-mongodb.tf
terraform/azure-mssql-db-failover/azure-versions.tf
terraform/azure-mssql-db/provision/mssql-db-versions.tf
terraform/azure-mssql-failover/provision-mssql-failover.tf
terraform/azure-mssql-server/mssql-server-provision.tf
terraform/azure-mssql/provision-mssql.tf
terraform/azure-mysql/provision-mysql.tf
terraform/azure-postgres/postgres-provision.tf
terraform/azure-redis/redis-provision.tf
terraform/azure-resource-group/resource-group-provision.tf
terraform/azure-storage/account-provision.tf

Updates to new major version of the terraform-provider-azurerm provider. In order to:
- be using a recent, supported version
- include any bug fixes
- hopefully reduce the frequency of errors deploying MS-SQL failover groups in examples tests
[#183376379](https://www.pivotaltracker.com/story/show/183376379)

chore: update terraform-provider-azurerm to v3

---

manifest.yml
terraform/azure-cosmosdb/provision-cosmosdb-sql.tf
terraform/azure-eventhubs/azure-eventhubs-bind.tf
terraform/azure-eventhubs/azure-eventhubs.tf
terraform/azure-mongodb/azure-mongodb.tf
terraform/azure-mssql-db-failover/azure-versions.tf
terraform/azure-mssql-db/provision/mssql-db-versions.tf
terraform/azure-mssql-failover/provision-mssql-failover.tf
terraform/azure-mssql-server/mssql-server-provision.tf
terraform/azure-mssql/provision-mssql.tf
terraform/azure-mysql/provision-mysql.tf
terraform/azure-postgres/postgres-provision.tf
terraform/azure-redis/redis-provision.tf
terraform/azure-resource-group/resource-group-provision.tf
terraform/azure-storage/account-provision.tf

This reverts commit b5cbc032f9c44cf9fe9360d9f9257ee2dcda548f.
The commit was causing test failures because the property `extended_auditing_policy` has been removed.
[#183376379](https://www.pivotaltracker.com/story/show/183376379)

chore: revert "chore: update terraform-provider-azurerm to v3"

---

azure-mssql.yml

This example is just a variation of the larger or medium one with a different size and no additional functionality. There is no need to test every possible combination.
Also, this example is one of the most costly ones by removing it we might reduce testing costs slightly.
* ~[ ] Have you added Release Notes in the docs repositories?~

chore: [MSSQL] remove xlarge example

---

manifest.yml

Expected order in manifest declaration: name, version source [...extra fields]
Otherwise the auto-bump providers job will modify the file erroneously
[#186276385](https://www.pivotaltracker.com/story/show/186276385)

fix: expected order in manifest declaration: name, version source

---

acceptance-tests/upgrade/upgrade_suite_test.go

Upgrade test from v1.3.0 and earlier started to fail because of a "preflight" check recently adding which ensures that the input looks right before pusing a broker/brokerpak app.

test: older versions don't have '.envrc' file

---

acceptance-tests/upgrade/update_and_upgrade_mssql_db_test.go
azure-mssql-db-failover-group.yml
azure-mssql-db.yml
manifest.yml
terraform/azure-cosmosdb/provision/versions.tf
terraform/azure-eventhubs/bind/versions.tf
terraform/azure-eventhubs/provision/versions.tf
terraform/azure-mongodb/provision/versions.tf
terraform/azure-mssql-db-failover/azure-versions.tf
terraform/azure-mssql-db/provision/mssql-db-versions.tf
terraform/azure-mssql-failover/provision/versions.tf
terraform/azure-mssql-server/provision/versions.tf
terraform/azure-mssql/provision/versions.tf
terraform/azure-mysql/provision/versions.tf
terraform/azure-postgres/provision/versions.tf
terraform/azure-redis/provision/versions.tf
terraform/azure-resource-group/provision/versions.tf
terraform/azure-storage/provision/main.tf
terraform/azure-storage/provision/versions.tf

Now that we no longer support subsume, it's possible to update the Azure Terraform provider to V3. Previously this was problematic as running an update/upgrade on service instances that supported subsume would try to run `terraform output` which failed as the schema used by the Azure provider V2/V3 has changed. With subsume no longer supported, we don't need to run `terraform output` (trigged by `tf_attribute`) and we don't see the error any more.
[#183376379](https://www.pivotaltracker.com/story/show/183376379)

chore: bump Azure Terraform provider to V3

---

.github/dependabot.yml

We see lots of Dependabot PR conflicts which are easy to resolve, but if we configure Dependabot to run at different times for different modules, then hopefully we will see fewer conflicts in the first place.

chore: spread out Dependabot updates

---

manifest.yml

In order to reduce the size of the brokerpak, obsolete Terraform providers have been removed. As a result, to get to this version through upgrading, you must upgrade to v1.6 first and upgrade all service instances to v1.6. This can be done via "cf upgrade-service", or for bulk upgrades consider the plugin: https://github.com/cloudfoundry/upgrade-all-services-cli-plugin You can then upgrade to this version, and again upgrade all the service instances.
[#186588913](https://www.pivotaltracker.com/story/show/186588913)

feat: restrict upgrade to v1.6 only

---

manifest.yml

I can't find any usages of the "null_resource" so we do not need this provider.
[#186588913](https://www.pivotaltracker.com/story/show/186588913)

chore: remove unused "null" provider

---

azure-mongodb.yml
integration-tests/mongodb_test.go
terraform-tests/cosmosdb_mongo_test.go
terraform/azure-mongodb/provision/main.tf
terraform/azure-mongodb/provision/variables.tf

[#186981808](https://www.pivotaltracker.com/story/show/186981808)
We started to see some errors related to 'unique' field being invalid for _id key. There is very little clarity online about the issue. More so, if we focus on Azure CosmoDB for MongoDB.
After some trial and error, it seems that mongodb instances created in location 'westus2' have started imposing this, while instances created in location 'westus' work without issues with the same configuration.
Changes in this commit is an attempt to cover our backs and be prepared in case Azure imposes this validation on all locations in the near future.
These changes should be backward compatible without any user intervention. Both, from the point of view of existing plans, and from the point of view of existing instances.
HOWEVER, we …

fix: mongodb the field 'unique' is not valid for _id

---

azure-mongodb.yml

[#186981808](https://www.pivotaltracker.com/story/show/186981808)
Related to PR:
- https://github.com/cloudfoundry/csb-brokerpak-azure/pull/676
Previously, example-test named `spring-music-mongo-db` was working without issues. It seems `westus` location is starting to throw the same kind of issues now too.

fix: example-test-spring-music-mongo-db-started-failing

---

Makefile
README.md
providers/terraform-provider-csbmssqldbrunfailover/Makefile

The same benefits can be achieved by simply launching an interactive docker session inside a supported image and running commands from there. This approach has some additional benefits
- Easier to maintain
- Debloats Makefile
- Less hidden magic
- Same code for local and containerised execution

chore: remove run-in-docker logic from Makefile

---

acceptance-tests/apps/mongodbapp/go.mod
acceptance-tests/apps/mssqlapp/go.mod
acceptance-tests/apps/mysqlapp/go.mod
acceptance-tests/apps/postgresqlapp/go.mod
acceptance-tests/apps/redisapp/go.mod
go.mod

Related PRs:
- https://github.com/cloudfoundry/csb-brokerpak-gcp/pull/1044

chore: specify go 1.22.0 in go.mod

---

Makefile
providers/terraform-provider-csbmssqldbrunfailover/Makefile

[#187027977](https://www.pivotaltracker.com/story/show/187027977)
Before Go 1.21:
- The go directive was advisory only; now it is a mandatory requirement
- The go directive didn't allow specifying patch versions
So, by specifying the patch version in go.mod:
- Noone can unknowingly test, run or build this project using an older version of go
- The required Go toolchain can be downloaded automatically
Therefore, checking the current go version in Makefile is no longer needed.

chore: stop checking go version in Makefile

---

dependency-manifest.yml
manifest.yml

[#187172990](https://www.pivotaltracker.com/story/show/187172990)
Version 3.94.0 for terraform-provider-azurerm caused issues in
redis acceptance_test/upgrade/update_and_upgrade_redis_test
https://github.com/cloudfoundry/csb-brokerpak-azure/commit/e154a5dcb82cfa251efa0abbd8202d0c0e348a31
We were getting error:
> BadRequest: The following updates can't be processed in one
single request, please send separate request to update them:
'properties.sku.capacity,properties.aadEnableDisable'
We still don't fully understand what is the root cause of the
issue. Because of that, **we prefer reverting the bump commit**
until we can guarantee that customer instances won't fail or be
blocked by this type of errors.
There is another PR with a workaround for the test, but take
into account that it …

chore: revert bump 3.94.0 for azure provider

---

dependency-manifest.yml
manifest.yml

[#187172990](https://www.pivotaltracker.com/story/show/187172990)
This is the second attempt to revert the bump. The first
attempt failed because we had not added v3.94.0 to the
list of versions to ignore. To learn more about this see:
- https://github.com/cloudfoundry/csb-brokerpak-azure/pull/705
- https://github.com/pivotal/cloud-service-broker-ci/pull/858
- https://github.com/pivotal/cloud-service-broker-ci/pull/859
Version 3.94.0 for terraform-provider-azurerm caused issues in
redis acceptance_test/upgrade/update_and_upgrade_redis_test
https://github.com/cloudfoundry/csb-brokerpak-azure/commit/e154a5dcb82cfa251efa0abbd8202d0c0e348a31
We were getting error:
> BadRequest: The following updates can't be processed in one
single request, please send separate request to update them: …

chore: revert bump 3.94.0 azure provider (2nd attempt)

---

azure-mssql-fog-run-failover.yml
terraform/azure-cosmosdb/provision/variables.tf
terraform/azure-eventhubs/bind/variables.tf
terraform/azure-eventhubs/provision/variables.tf
terraform/azure-mongodb/provision/variables.tf
terraform/azure-mssql-db-failover/azure-provider.tf
terraform/azure-mssql-db-failover/mssql-db-fog-variables.tf
terraform/azure-mssql-db-failover/run-failover/run-failover-providers.tf
terraform/azure-mssql-db-failover/run-failover/variables.tf
terraform/azure-mssql-db/bind/mssql-bind-variables.tf
terraform/azure-mssql-db/provision/mssql-db-providers.tf
terraform/azure-mssql-db/provision/mssql-db-variables.tf
terraform/azure-mssql-failover/provision/variables.tf
terraform/azure-mssql-server/provision/variables.tf
terraform/azure-mssql/bind/variables.tf
terraform/azure-mssql/provision/variables.tf
terraform/azure-mysql/bind/variables.tf
terraform/azure-mysql/provision/variables.tf
terraform/azure-postgres/bind/variables.tf
terraform/azure-postgres/provision/variables.tf
terraform/azure-redis/provision/variables.tf
terraform/azure-storage/provision/variables.tf

By annotating terraform variables that contain sensitive information, we ensure that they are not printed out in error messages.
This re-implements #356 which previously had to be reverted due to not being supported by the version of terraform at the time. Note that we have not chosen to annotate IDs (e.g. user IDs) as sensitive, but only secrets/passwords. This is because printing out an ID in an error message can be very helpful.
[#183474479](https://www.pivotaltracker.com/story/show/183474479)

chore: annotate sensitive terraform varaibles

---

.github/labeler.yml
.github/release.yml
.github/workflows/labeler.yml

Each PR will be labeled depending on the name of the branch according to convertional commits. The release notes will be clasified based on the type of PRs.

chore: Add labeler to improve the release notes. 

---

acceptance-tests/apps/mongodbapp/go.mod
acceptance-tests/apps/mongodbapp/go.sum
acceptance-tests/apps/mongodbapp/internal/app/app.go
acceptance-tests/apps/mongodbapp/internal/app/fetch_document.go
acceptance-tests/apps/mongodbapp/internal/app/list_collections.go
acceptance-tests/apps/mongodbapp/internal/app/store_document.go
acceptance-tests/apps/mssqlapp/go.mod
acceptance-tests/apps/mssqlapp/go.sum
acceptance-tests/apps/mssqlapp/internal/app/app.go
acceptance-tests/apps/mssqlapp/internal/app/get.go
acceptance-tests/apps/mssqlapp/internal/app/set.go
acceptance-tests/apps/postgresqlapp/go.mod
acceptance-tests/apps/postgresqlapp/go.sum
acceptance-tests/apps/postgresqlapp/internal/app/app.go
acceptance-tests/apps/postgresqlapp/internal/app/get.go
acceptance-tests/apps/postgresqlapp/internal/app/set.go

Go 1.22 has an improved HTTP router that means we don't need the Chi router any more.
The Go 1.22 routing automatically adds a HEAD handler to every path that has a GET handler, so where we used to explicitly handle both methods we now only add the GET explicitly.
[#187470327](https://www.pivotaltracker.com/story/show/187470327)

test: remove Chi dependency from test apps

---

azure-mysql.yml
azure-postgresql.yml
integration-tests/mysql_test.go
integration-tests/postgre_sql_test.go

Both services are on the retirement path from Azure and should no longer be used to create new instances. They will be replaced by flexible server offerings.
https://learn.microsoft.com/en-gb/azure/postgresql/single-server/whats-happening-to-postgresql-single-server
https://learn.microsoft.com/en-gb/azure/mysql/single-server/whats-happening-to-mysql-single-server
[#187634075](https://www.pivotaltracker.com/story/show/187634075)

chore: Retire MySQL and PostgreSQL services

---

.github/dependabot.yml

These changes are to optimise the use of the CI. Every full run through the pipeline requires several AWS environments and several hours of tests.

chore: Test dependencies are updated only once a week

---

acceptance-tests/helpers/brokers/default.go

currently running these tests against as tile based deployment errors with:
```
• [PANICKED] [0.236 seconds]
Redis [It] can be accessed by an app [redis]
/tmp/build/135320cb/brokerpak/acceptance-tests/redis_test.go:14
[PANICKED] Test Panicked
In [It] at: /tmp/build/135320cb/brokerpak/acceptance-tests/helpers/brokers/default.go:39 @ 06/21/24 08:58:01.135
could not determine default broker name
Full Stack Trace
```
it seems that this is caused by the brokerpak tests expecting the name being set to `broker-cf-test`. The new broker is called `cloud-service-broker-azure` in a tile deployment and thus the tests panic.
[#187498188]

test: enable running against tile based deployment

---

acceptance-tests/helpers/brokers/env.go
scripts/push-broker.sh

The new environment variable is not automatically read from the .envrc file by our implemented GoLang logic when creating a new broker in our acceptance tests.
[#187918632](https://www.pivotaltracker.com/story/show/187918632)

test: force the environment variable

---

terraform/azure-eventhubs/bind/versions.tf
terraform/azure-eventhubs/provision/versions.tf
terraform/azure-mssql-db-failover/azure-versions.tf
terraform/azure-mssql-db/bind/mssql-bind-versions.tf
terraform/azure-mssql-db/provision/mssql-db-versions.tf
terraform/azure-mssql-failover/provision/versions.tf
terraform/azure-mssql-server/provision/versions.tf
terraform/azure-mssql/bind/versions.tf
terraform/azure-mssql/provision/versions.tf
terraform/azure-postgresql-flexible-server/bind/versions.tf
terraform/azure-postgresql-flexible-server/provision/versions.tf
terraform/azure-redis/provision/versions.tf
terraform/azure-resource-group/provision/versions.tf
terraform/azure-storage/provision/versions.tf

The operator is a convenient shorthand that allows the rightmost component of a version to increment. The fix also corrects the Terraform test by downloading the current provider version.

feat: use operator ~> as version constraint

---

acceptance-tests/upgrade/update_and_upgrade_mongodb_test.go
acceptance-tests/upgrade/update_and_upgrade_redis_test.go
acceptance-tests/upgrade/upgrade_suite_test.go

The contract between CI infrastructure and the tests has historically been that resource groups will be provided. This undoes a change that was made to create a resource group in the test, which does not allow tests to run in parallel because they create the same resource group.

test: use pre-existing resource groups

---

acceptance-tests/helpers/az/start.go
acceptance-tests/mongodb_test.go
acceptance-tests/redis_test.go
acceptance-tests/upgrade/update_and_upgrade_mongodb_test.go
acceptance-tests/upgrade/update_and_upgrade_redis_test.go

The az.Start() helper actually waited for a command to finish

test: rename test helper to reflect what it does

---

manifest.yml
terraform/azure-mongodb/provision/versions.tf
terraform/azure-mssql-db-failover/azure-versions.tf
terraform/azure-mssql-db/provision/mssql-db-versions.tf
terraform/azure-redis/provision/versions.tf

This reverts commit 85fab72aa084cfba9bcc0aa321d763142cc4952b.
Sometimes updating a major version "just works" but in this case a lot of tests failed, so we need to take time to test every service manually

Revert "build(deps): bump Azure terraform provider to v4 (#888)"

---

acceptance-tests/helpers/services/delete.go
acceptance-tests/mssql_fog_existing_test.go
acceptance-tests/mssql_server_and_db_test.go
acceptance-tests/mssql_server_pair_and_fog_db_test.go
acceptance-tests/passwordrotation_test.go
acceptance-tests/upgrade/update_and_upgrade_mongodb_test.go
acceptance-tests/upgrade/update_and_upgrade_mssql_db_failover_group_existing_test.go
acceptance-tests/upgrade/update_and_upgrade_mssql_db_failover_group_test.go
acceptance-tests/upgrade/update_and_upgrade_mssql_db_test.go
acceptance-tests/upgrade/update_and_upgrade_redis_test.go

We can only have 5 instances of our test broker running. Tests that use the test broker can see 'failed to allocate' errors. This is because in the case of a failed creation of a service in our tests will fail to clean up the test broker, causing other test runs to fail.

chore: Fixes broker 'failed to allocate' test errors

---

acceptance-tests/helpers/services/upgrade.go
acceptance-tests/upgrade/update_and_upgrade_mssql_db_failover_group_test.go
terraform/azure-mssql-db-failover/mssql-db-fog-main.tf
terraform/azure-mssql-db-failover/mssql-db-fog-outputs.tf

The resource "azurerm_sql_failover_group" has been deprecated and is removed in the next version of the AzureRM provider. In order to prepare for this, we are replacing it with the new alternative "azurerm_mssql_failover_group". Because OpenTofu will run the delete of "azurerm_sql_failover_group" in parallel with the creation of "azurerm_mssql_failover_group", the upgrade of service instances will fail at the first attempt. But it will succeed on a second attempt. This is not an ideal behavior, but as long as it's expected it's easy to deal with, and alternatives come with a different set of tradeoffs (principally needing to re-bind service instances, or re-engineering the core broker).
Requires core broker fix: https://github.com/cloudfoundry/cloud-service-broker/pull/1179

feat: replace sql_failover_group with mssql_failover_group

---

providers/terraform-provider-csbmssqldbrunfailover/csbmssqldbrunfailover/resource_run_failover_test.go
providers/terraform-provider-csbmssqldbrunfailover/go.mod
providers/terraform-provider-csbmssqldbrunfailover/testhelpers/failover.go
providers/terraform-provider-csbmssqldbrunfailover/testhelpers/random.go

Following on from commit 965ad7cec5187a9f093a7df33c7dace2b28351ca, it was observed that it's possible to completely drop a dependency on a uuid generation package

chore: drop the uuid dependency

---

acceptance-tests/helpers/brokers/delete.go
acceptance-tests/helpers/brokers/env.go
acceptance-tests/upgrade/update_and_upgrade_mssql_db_failover_group_existing_test.go

- As well as testing the "existing" plan, it used another plan too, and therefore needed changes because of #922
- Also explicitly frees backing database on broker delete, which will hopefully reduce leaking of resources

test: fix mssql_db_failover_existing test

---

acceptance-tests/upgrade/update_and_upgrade_mongodb_test.go

Tha property is not allowed until we release

test: the version was injected in the released CSB

---

acceptance-tests/helpers/mssqlserver/mssqlserver.go
acceptance-tests/mssql_fog_existing_test.go
acceptance-tests/mssql_server_and_db_test.go
acceptance-tests/mssql_server_pair_and_fog_db_test.go
acceptance-tests/upgrade/update_and_upgrade_mssql_db_failover_group_existing_test.go
acceptance-tests/upgrade/update_and_upgrade_mssql_db_failover_group_test.go
acceptance-tests/upgrade/update_and_upgrade_mssql_db_test.go
terraform/azure-mongodb/provision/main.tf

- In a test, there's no value in passing around context.Context if you don't do anything with it
- In a test, there's no value in returning an error if all callers will fail on the error
- It's better to use Ginkgo's DeferCleanup() than a Go defer() as it has better logging

test: simplify MS-SQL tests

---

manifest.yml

There is a behaviour change in OpenTofu v1.10, and while we work out how to deal with it, we will switch back to v1.9.1
https://github.com/opentofu/opentofu/issues/2977

chore: revert to OpenTofu v1.9
