cloudfoundry/csb-brokerpak-azure

terraform/azure-mssql-db-failover/mssql-db-fog-main.tf

Fixes https://github.com/cloudfoundry-incubator/csb-brokerpak-azure/issues/8

Make Azure SQL FOG resource depend on secondary DB creation

---

terraform/azure-mssql-db/bind/mssql-bind-main.tf

Implements https://github.com/cloudfoundry-incubator/csb-brokerpak-azure/issues/13

Add Azure SQL users to db_owner role

---

dependency-manifest.yml

[#178246686](https://www.pivotaltracker.com/story/show/178246686)

Norsk setup

---

acceptance-tests/apps/mssqlapp/internal/app/app.go
acceptance-tests/apps/mssqlapp/internal/app/create_schema.go
acceptance-tests/apps/mssqlapp/internal/app/drop_schema.go
acceptance-tests/apps/mssqlapp/internal/app/get.go
acceptance-tests/apps/mssqlapp/internal/app/set.go
acceptance-tests/helpers/app_push.go
acceptance-tests/helpers/app_start.go
acceptance-tests/helpers/binding.go
acceptance-tests/helpers/service.go
acceptance-tests/helpers/service_key.go
acceptance-tests/mssql/mssql_failover_group_test.go
acceptance-tests/mssql/mssql_suite_test.go
acceptance-tests/mssql/mssql_test.go

Extended test to cover failover scenario
[#178886030](https://www.pivotaltracker.com/story/show/178886030)

test: Ginkgo failover-group test should test failover

---

azure-mssql-db.yml

[#179317385](https://www.pivotaltracker.com/story/show/179317385)

fix: allow databases smaller than 1GB to be subsumed

---

azure-mssql-db-failover.yml

[#179580307](https://www.pivotaltracker.com/story/show/179580307)

Remove default value for retention_days on import

---

azure-mssql-failover.yml
terraform/azure-mssql-failover/provision-mssql-failover.tf

[#180210710](https://www.pivotaltracker.com/story/show/180210710)

fix: Add required properties to enable mssql fog serverless

---

acceptance-tests/upgrade/update_and_upgrade_mongodb_test.go

[#180325770](https://www.pivotaltracker.com/story/show/180325770)

test: ensure mongodb data present after unbind/bind

---

acceptance-tests/helpers/apps/http.go

We have seen issues on MongoDB where we put some data with one app, then
fail to get it with a second app. We think this may be an issue with
eventual consistency in MongoDB, so as an experiment have added some
retry logic to get HTTP GET step so that it will keep trying until it
gets an HTTP 200 OK or times out after a minute.
[#181126724](https://www.pivotaltracker.com/story/show/181126724)

test: HTTP GET should retry

---

acceptance-tests/helpers/bindings/bind.go
acceptance-tests/helpers/bindings/unbind.go
acceptance-tests/helpers/servicekeys/create.go
acceptance-tests/helpers/servicekeys/delete.go
acceptance-tests/helpers/services/create.go
acceptance-tests/helpers/services/delete.go
acceptance-tests/helpers/services/services.go
acceptance-tests/helpers/services/update.go

[#181126699](https://www.pivotaltracker.com/story/show/181126699)

test: review timeouts for service commands

---

azure-mssql-db-failover.yml

[#180586187](https://www.pivotaltracker.com/story/show/180586187)

fix: add tf_attribute for fog subsume flow

---

Makefile
README.md
tools/psqlcmd/Makefile
tools/sqlfailover/Makefile

build: makefile targets work with docker or go

---

acceptance-tests/apps/mongodbapp/internal/app/app.go
acceptance-tests/apps/mongodbapp/internal/app/store_document.go

[#182399154](https://www.pivotaltracker.com/story/show/182399154)

test: ttl force to prevent data from expiring

---

acceptance-tests/helpers/azure/resource_id.go
acceptance-tests/helpers/environment/server.go
acceptance-tests/helpers/serverpairs/serverpairs.go
acceptance-tests/mssql_db_subsume_test.go
acceptance-tests/mssql_fog_db_subsume_test.go
acceptance-tests/mssql_fog_existing_test.go
acceptance-tests/mssql_server_pair_and_fog_db_test.go

test: increase usage of shared helpers

---

azure-cosmosdb-sql.yml
azure-eventhubs.yml
azure-mongodb.yml
azure-mssql-failover.yml
azure-mssql-server.yml
azure-mssql.yml
azure-mysql.yml
azure-postgres.yml
azure-redis.yml
azure-resource-group.yml
azure-storage-account.yml
docs/draft-release-notes.md

feat: Use text field in the location property

---

Makefile
README.md
integration-tests/cosmosdb_sql_test.go
integration-tests/eventhubs_test.go
integration-tests/integration_test_suite_test.go
integration-tests/mongodb_test.go
integration-tests/mssql_failover_test.go
integration-tests/mssql_server_test.go
integration-tests/mssql_test.go
integration-tests/mysql_test.go
integration-tests/postgre_sql_test.go
integration-tests/redis_test.go
integration-tests/resource_group_test.go
integration-tests/storage_account_test.go

test: add integration tests

---

acceptance-tests/helpers/brokers/create.go

[#182596553](https://www.pivotaltracker.com/story/show/182596553)
~~* [ ] Have you added Draft Release Notes in `docs/draft-release-notes.md`?~~

test: increase app memory to avoid failure

---

azure-mssql-db-failover.yml

[#182596553](https://www.pivotaltracker.com/story/show/182596553)
~~* [ ] Have you added Draft Release Notes in `docs/draft-release-notes.md`?~~

fix: amend failover service def to include all files

---

acceptance-tests/upgrade/update_and_upgrade_mssql_db_failover_group_test.go

test: rename test to match service offering that it tests

---

acceptance-tests/helpers/services/upgrade.go
acceptance-tests/upgrade/update_and_upgrade_mongodb_test.go

test(MongoDB): check bindings work after upgrade failure

---

acceptance-tests/helpers/brokers/update.go
acceptance-tests/upgrade/update_and_upgrade_mongodb_test.go
acceptance-tests/upgrade/update_and_upgrade_mssql_db_failover_group_test.go
acceptance-tests/upgrade/update_and_upgrade_mssql_db_test.go
acceptance-tests/upgrade/update_and_upgrade_mssql_failover_group_test.go

test(mssql): fix issues with ancient upgrade tests

---

acceptance-tests/helpers/services/upgrade.go

[#182757139](https://www.pivotaltracker.com/story/show/182757139)

test: Skip upgrades when none are available

---

scripts/push-broker.sh

Rather than running "cf set-env" many times, variables and their values
are added to the manifest
[#182771270](https://www.pivotaltracker.com/story/show/182771270)

chore: push the broker faster

---

scripts/push-broker.sh

chore: remove Google variables from Azure script

---

docs/draft-release-notes.md

docs: Clean up draft docs

---

acceptance-tests/apps/cosmosdbapp/package-lock.json
acceptance-tests/apps/cosmosdbapp/package.json

Reverts cloudfoundry/csb-brokerpak-azure#329

Revert "chore(deps): bump @azure/cosmos from 3.16.4 to 3.17.0 in /acceptance-tests/apps/cosmosdbapp"

---

azure-cosmosdb-sql.yml
azure-mongodb.yml

Both https://www.pivotaltracker.com/story/show/178910443 and https://www.pivotaltracker.com/story/show/178945167 mentioned in the commented TODO were accepted.
Signed-off-by: Konstantin Semenov <ksemenov@pivotal.io>

test: Uncommented previously failing examples

---

Makefile
terraform/azure-cosmosdb/provision-cosmosdb-sql.tf
terraform/azure-eventhubs/azure-eventhubs-bind.tf
terraform/azure-eventhubs/azure-eventhubs.tf
terraform/azure-mongodb/azure-mongodb.tf
terraform/azure-mssql-db-failover/mssql-db-fog-outputs.tf
terraform/azure-mssql-db-failover/run-failover/run-failover-providers.tf
terraform/azure-mssql-db/bind/mssql-bind-variables.tf
terraform/azure-mssql-db/provision/mssql-db-providers.tf
terraform/azure-mssql-db/provision/mssql-db-variables.tf
terraform/azure-mssql-failover/provision-mssql-failover.tf
terraform/azure-mssql-server/mssql-server-provision.tf
terraform/azure-mssql/bind-mssql.tf
terraform/azure-mssql/provision-mssql.tf
terraform/azure-mysql/bind-mysql.tf
terraform/azure-mysql/provision-mysql.tf
terraform/azure-postgres/postgres-provision.tf
terraform/azure-postgres/postgresql-bind.tf
terraform/azure-redis/redis-provision.tf
terraform/azure-resource-group/resource-group-provision.tf
terraform/azure-storage/account-provision.tf

Also reverted: chore: apply and enforce "terraform fmt" (#360)

chore(revert): mark sensitive values in var inputs and outputs (#356)

---

Makefile
terraform/azure-mssql-db-failover/mssql-db-fog-outputs.tf

Repeat of #360 which was reverted

chore: apply and enforce "terraform fmt"

---

azure-cosmosdb-sql.yml
azure-eventhubs.yml
azure-mongodb.yml
azure-mssql-db-failover.yml
azure-mssql-db.yml
azure-mssql-failover.yml
azure-mssql-fog-run-failover.yml
azure-mssql-server.yml
azure-mssql.yml
azure-mysql.yml
azure-postgres.yml
azure-redis.yml
azure-resource-group.yml
azure-storage-account.yml
manifest.yml

- remove unused plan_input default values
- fix formatting: trailing spaces, inconsistent indentation
[#183701212](https://www.pivotaltracker.com/story/show/183701212)

chore: cleanup YAML

---

integration-tests/cosmosdb_sql_test.go
terraform-tests/cosmosdb_sql_test.go

[#183773752](https://www.pivotaltracker.com/story/show/183773752)
Tests for #381

test: Added tests for private endpoint and resource group

---

.cfignore
acceptance-tests/upgrade/update_and_upgrade_redis_test.go

[#183888727](https://www.pivotaltracker.com/story/show/183888727)

chore: use deprecated plans

---

acceptance-tests/helpers/apps/push.go

The contribtor of #351 left the team before being able to act on the code review feedback

test: tidy up after #351

---

azure-cosmosdb-sql.yml
azure-eventhubs.yml
azure-mongodb.yml
azure-mssql-db-failover.yml
azure-mssql-failover.yml
azure-mssql-server.yml
azure-mssql.yml
azure-mysql.yml
azure-postgres.yml
azure-redis.yml
azure-storage-account.yml

[#184613881](https://www.pivotaltracker.com/story/show/184613881)

chore: update property types

---

go.mod

It seems to have an extra, unexpected section

chore: tidy up go.mod file

---

manifest.yml

This reverts commit 33867d75b9f99cd755c5b8ee995b143ce5291fae.
[#183376494](https://www.pivotaltracker.com/story/show/183376494)

chore: Revert "feat: upgrade to terraform 1.4 (#472)"

---

acceptance-tests/helpers/apps/http.go
acceptance-tests/helpers/cf/start.go

Moved to an equivalent that's a bit easier to read
[#184673945](https://www.pivotaltracker.com/story/show/184673945)

chore: update method used for logging in tests

---

Makefile
providers/terraform-provider-csbmssqldbrunfailover/Makefile
providers/terraform-provider-csbsqlserver/Makefile

chore: Add make target to compute code coverage

---

integration-tests/integration_test_suite_test.go
integration-tests/mssql_db_failover_group_test.go
integration-tests/mssql_db_test.go

chore: add missing integration tests

---

manifest.yml

[#183376494](https://www.pivotaltracker.com/story/show/183376494)

chore: upgrade terraform to latest 1.4 version

---

acceptance-tests/upgrade/multi_step_upgrade_mssql_db_test.go
acceptance-tests/upgrade/upgrade_suite_test.go

[#183376494](https://www.pivotaltracker.com/story/show/183376494)
~~* [ ] Have you added Release Notes in the docs repositories?~~

test: add test for upgrades passing through an intermediate version

---

Makefile

[#185955999](https://www.pivotaltracker.com/story/show/185955999)
shell instruction will mask any error happening in GET_CSB command such as errors resolving dependencies due to some network issue

fix: [CI] build-broker-brokerpak masking errors

---

Makefile

We remove the sentence to have green pipelines. We will unify providers and add the test in another task.
[#185100152](https://www.pivotaltracker.com/story/show/185100152)

chore: SQL Server TF provider needs docker in CI

---

manifest.yml

[#186276385](https://www.pivotaltracker.com/story/show/186276385)

fix: incorrect manifest after automatic bump

---

dependency-manifest.yml
manifest.yml

fix: incorrect cyrilgdn Terraform provider version 

---

acceptance-tests/mssql_failover_group_test.go
acceptance-tests/mssql_fog_existing_test.go
acceptance-tests/mssql_server_and_db_test.go
acceptance-tests/mssql_server_pair_and_fog_db_test.go
acceptance-tests/mssql_test.go

[#186434321](https://www.pivotaltracker.com/story/show/186434321)

test: ms-sql clarify meaning of labels

---

terraform/azure-mssql-db-failover/mssql-db-fog-outputs.tf
terraform/azure-mssql-server/mssql-server-provision.tf
terraform/azure-mysql/bind-mysql.tf
terraform/azure-postgres/postgresql-bind.tf

[#186442543](https://www.pivotaltracker.com/story/show/186442543)

fix: flag sensitive output values

---

terraform/azure-mysql/bind-mysql.tf
terraform/azure-postgres/postgresql-bind.tf

[#186442543](https://www.pivotaltracker.com/story/show/186442543)
~~* [ ] Have you added Release Notes in the docs repositories?~~

chore: flag sensitive values in terraform outpus

---

terraform-tests/cosmosdb_mongo_test.go
terraform-tests/cosmosdb_sql_test.go
terraform-tests/redis_test.go

[#186495361](https://www.pivotaltracker.com/story/show/186495361)
* [~~ ] Have you added Release Notes in the docs repositories?~~

fix: change terraform test folder execution

---

terraform/azure-mysql/bind/versions.tf

chore: fix empty terraform template files

---

manifest.yml

chore: upgrade terraform to latest open source version

---

.github/dependabot.yml

This will result in more PRs, but it will bring us close to always being ready to release.

chore: run Dependabot daily

---

docs/service-offerings.md

fix: replace reference to obsolete domain

---

dependency-manifest.yml
manifest.yml

chore: revert bump azure provider

---

.github/dependabot.yml
.github/labeler.yml
.github/release.yml

chore: Rely on dependabot to label its PRs

---

terraform-tests/README.md

[#187200917](https://www.pivotaltracker.com/story/show/187200917)

docs: update documentation to not mention terraform anymore

---

acceptance-tests/helpers/apps/push.go
go.mod

- Replaced with gopkg.in/yaml.v3
- Tidied up go.mod file to have the two expected sections (direct and
indirect dependencies), rather than three
[#187455023](https://www.pivotaltracker.com/story/show/187455023)

chore(deps): bump gopkg.in/yaml.v2

---

acceptance-tests/helpers/brokers/create.go
acceptance-tests/helpers/brokers/update.go
acceptance-tests/upgrade/update_and_upgrade_cosmos_test.go
acceptance-tests/upgrade/update_and_upgrade_mongodb_test.go
acceptance-tests/upgrade/update_and_upgrade_mssql_db_failover_group_existing_test.go
acceptance-tests/upgrade/update_and_upgrade_mssql_db_failover_group_test.go
acceptance-tests/upgrade/update_and_upgrade_mssql_db_test.go
acceptance-tests/upgrade/update_and_upgrade_mssql_failover_group_test.go
acceptance-tests/upgrade/update_and_upgrade_mssql_test.go
acceptance-tests/upgrade/update_and_upgrade_mysql_test.go
acceptance-tests/upgrade/update_and_upgrade_postgresql_test.go
acceptance-tests/upgrade/update_and_upgrade_redis_test.go
acceptance-tests/upgrade/update_and_upgrade_storage_test.go

fix: Use envrc when running upgrade tests

---

acceptance-tests/upgrade/update_and_upgrade_mongodb_test.go
acceptance-tests/upgrade/update_and_upgrade_mssql_db_failover_group_test.go
acceptance-tests/upgrade/update_and_upgrade_mssql_db_test.go
acceptance-tests/upgrade/update_and_upgrade_mssql_failover_group_test.go
acceptance-tests/upgrade/update_and_upgrade_mssql_test.go
acceptance-tests/upgrade/update_and_upgrade_postgresql_test.go

test: Remove ancient tests that are no longer run on CI

---

go.mod
providers/terraform-provider-csbmssqldbrunfailover/csbmssqldbrunfailover/resource_run_failover_test.go
providers/terraform-provider-csbmssqldbrunfailover/testhelpers/failover.go

[#187659119](https://www.pivotaltracker.com/story/show/187659119)

chore: replace non maintain uuid package

---

azure-postgresql-flexible-server.yml
integration-tests/mssql_db_failover_group_test.go

docs: Update the description for `private_dns_zone_id`

---

manifest.yml

feat: Update tofu to latest v1.7.2

---

acceptance-tests/upgrade/update_and_upgrade_cosmos_test.go
acceptance-tests/upgrade/update_and_upgrade_mongodb_test.go
acceptance-tests/upgrade/update_and_upgrade_mssql_db_test.go
acceptance-tests/upgrade/update_and_upgrade_mssql_failover_group_test.go
acceptance-tests/upgrade/update_and_upgrade_mssql_test.go
acceptance-tests/upgrade/update_and_upgrade_mysql_test.go
acceptance-tests/upgrade/update_and_upgrade_postgresql_flexible_server_test.go
acceptance-tests/upgrade/update_and_upgrade_postgresql_test.go
acceptance-tests/upgrade/update_and_upgrade_redis_test.go
acceptance-tests/upgrade/update_and_upgrade_storage_test.go

Also we now know that it is possible to do a noop update so replacing all updates with noop updates to make tests quicker
[#187814867](https://www.pivotaltracker.com/story/show/187814867)

test: Adding test assertions to validate bindings work after an upgrade

---

acceptance-tests/helpers/environment/metadata.go

[#187846697](https://www.pivotaltracker.com/story/show/187846697)

chore: Remove unused legacy broker MASB metadata

---

manifest.yml

feat: Update tofu to latest v1.8.0

---

azure-mssql-server.yml
azure-mssql.yml
azure-redis.yml
azure-resource-group.yml

chore: remove examples

---

acceptance-tests/helpers/az/start.go
acceptance-tests/helpers/environment/metadata.go
acceptance-tests/helpers/mssqlserver/mssqlserver.go
acceptance-tests/mongodb_test.go
acceptance-tests/mssql_fog_existing_test.go
acceptance-tests/mssql_server_and_db_test.go
acceptance-tests/mssql_server_pair_and_fog_db_test.go
acceptance-tests/upgrade/update_and_upgrade_mongodb_test.go
acceptance-tests/upgrade/update_and_upgrade_mssql_db_failover_group_existing_test.go
acceptance-tests/upgrade/update_and_upgrade_mssql_db_failover_group_test.go
acceptance-tests/upgrade/update_and_upgrade_mssql_db_test.go

https://vmw-jira.broadcom.net/browse/TPCF-31592

chore: changed acceptance tests to work with tas-lites

---

acceptance-tests/mongodb_test.go
acceptance-tests/mssql_fog_existing_test.go
acceptance-tests/mssql_server_and_db_test.go
acceptance-tests/mssql_server_pair_and_fog_db_test.go
acceptance-tests/passwordrotation_test.go
acceptance-tests/redis_test.go

- Notes which tests do and do not use default broker
- Adjust labels to match tested services

test: improve test labels and descriptions

---

acceptance-tests/passwordrotation_test.go

It should have tested the broker it created and modified, but previously it tested another broker instead

test: password rotation test acted on wrong broker

---

acceptance-tests/upgrade/update_and_upgrade_mongodb_test.go

This reverts commit ddf29a61226950e732a69e3c85665449ec539aa3.

Revert "test: the version was injected in the released CSB (#970)"

---

acceptance-tests/upgrade/update_and_upgrade_mssql_db_test.go

A Ginkgo DeferCleanup() is run _after_ a test finishes A Go defer() is run as a function ends
A change was made in commit aec88cbcce2f67a8385dbeb3365fd225f3ed27e3 that changed a defer() into a DeferCleanup(), which had the side-effect of changing cleanup order, and caused cleanup to fail.
This was resolved by consistently using DeferCleanup() in that test.

chore: consistently use DeferCleanup()

---

acceptance-tests/helpers/apps/prebuild.go
acceptance-tests/helpers/brokers/create.go
acceptance-tests/helpers/brokers/envrc.go
acceptance-tests/helpers/brokers/update.go
terraform-tests/helpers/resource_changes.go

The modernize command replaces old constructs with simpler, updated ones.
Command is:
go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -fix -test ./...

chore: apply fixes from Go modernize command
